Add plots, statistics and basic recommendations
Alexander-Serov/tinkoff_analysis pull request #3
Opened 2020-04-18 20:46 UTC by Alexander-Serov

2020-06-24 13:57 UTC, sserov requested changes
Okay, needs some elaboration and formalization

2020-06-24 13:57 UTC, sserov commented on .gitignore
> +token
Okay, all utility files and folders as well as data files should be ignored

2020-06-24 13:57 UTC, sserov commented on README.md
> +A solution using `tinkoff-api` investments for market situation analysis
```suggestion
A solution using `tinkoff-api` investments and [`open-api-python-client`](https://github.com/Awethon/open-api-python-client) python client for market situation analysis
```

2020-06-24 13:57 UTC, sserov commented on main-analysis.py
> +"""
No newline at the end

2020-06-24 13:57 UTC, sserov commented on main-recommend.py
> +from analysis import History
Simple interface to the recommendations, ok

2020-06-24 13:57 UTC, sserov commented on requirements.txt
> +colorama
```suggestion
colorama
numpy
pytz
```

Need to include also

```
openapi_client
openapi_genclient
```
?

2020-06-24 13:57 UTC, sserov commented on main-analysis.ipynb
> +{
Simple examples and plots. There are some strange leaps from 0 to 80% in FXWO (?) and some other tickers. Visualization with all the tickers in one plot is rather hard to read. Maybe we should use Plotly in future.

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +from openapi_client import openapi
A lot of unused imports

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +# Load the token
There is a section outside the functions. Maybe it's better to move it into init function or constructor of general class

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +        get_all_etfs.etfs = market.market_etfs_get().payload.instruments
Global variables in the module is not a good practice. Suggest to wrap it into a class

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +        get_all_etfs.etfs = market.market_etfs_get().payload.instruments
Function members are also not needed here. Suggest to make the function a class method which will modify class members

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +        df = pd.DataFrame.from_dict(candles_dict)
from_dict gets list instead of dict

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +        if figi not in obsolete_tickers.values():
What's the problem with obsolete tickers?

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +@lru_cache(maxsize=1000)
Cache?

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +    try:
Why here there is exceptions processing but in the previous function there isn't one? What's the puffnya with obsolete tickers?

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +    Get history _data with a given interval for all available ETFs.
Missing parameters in docstring

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +        if 'ticker' not in one_etf_history.columns:
How there can be different sets of columns in returned dataframes?

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +                         weeks=52),
A strange end of line

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +        # Merge into the large table
Not merge but concat?

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +    need_divide = length > one_period
Unused variable need divide

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +    Parameters
Different format of docstring?

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +        return np.nan
Why np.nan for obsolete tickers? They cannot be processed at all, can they?

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +    History.update() # to update the local database of prices
Meaning an instance of the class here?

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +            self._data.drop(self._data[pd.isna(self._data.time)].index, inplace=True)
For what should we store rows with nan timestamps and drop them during each load? Maybe it's better to kill them before saving (the are already dropped in ```def get_etfs_daily_history```)

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +            self._data.time = pd.to_datetime(self._data.time)
Can be moved into read_csv (see ```parse_dates``` parameter in https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html)

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +                    success = False
```suggestion
                    print(f"Unable to rename {tmp_file} into {file}")
                    success = False
```

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +        return success
```success = False``` are not needed because exceptions are raised in these cases

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +        self._tickers = tickers
And why do we update the tickers list in all cases even if reload is not needed?

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +            old_data = copy.deepcopy(self._data)
Why not to make ```pd.concat``` and then ```drop_duplicates```? It also should not spoil date columns in theory

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +                                                     filter_52w, ['figi', 'h']].groupby(
Strange identation

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +        :param position what time of day (o, c, h, l) to use to
What are o, c, h, l?

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +        Fetch the latest _data from server starting from 2 last known days.
From 2 last known days?

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +                          self._data.loc[self._data.time <= filter_1d, ['figi', position]].groupby(
```suggestion
                          self._data.loc[self._data.time >= filter_1d, ['figi', position]].groupby(
```

A typo?

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +            if (set(figis) - set(value.keys()) - set(obsolete_tickers.values())):
Redundant parentheses? Why does this warning emerge while running? What figis are not present?

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +        for figi in statistics_sorted.index:
Maybe we can do this without explicit loop by figis, simply by loc for our conditions?

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +    def recommend_other(self, update: bool = True, _print=False, reload=False):
Too many code repetition. Needs to be refactored according to TODO

2020-06-24 13:57 UTC, sserov commented on analysis.py
> +               f'{THRESHOLD_1D_CHG:.2f}):']
1 day change in the message and in criteria but ```1d_chg_percent``` printed in the second part of the message

2020-06-24 14:09 UTC, sserov commented
@Alexander-Serov

2021-03-14 13:59 UTC, Alexander-Serov commented on .gitignore
> +token
So it's OK for you or something is missing?

2021-03-14 13:59 UTC, Alexander-Serov commented on requirements.txt
> +colorama
If we add those two, pip install will fail. I don't think they are on pip.
I think they should rather be in the readme.

2021-03-14 13:59 UTC, Alexander-Serov commented on .gitignore
> +token
Так что-то еще хочешь добавить или как?

2021-03-14 13:59 UTC, Alexander-Serov commented on main-analysis.py
> +"""
Поправлю

2021-03-14 13:59 UTC, Alexander-Serov commented on main-recommend.py
> +from analysis import History
К чему этот комментарий?

2021-03-14 13:59 UTC, Alexander-Serov commented on analysis.py
> +from openapi_client import openapi
Починил.

2021-03-14 13:59 UTC, Alexander-Serov commented on analysis.py
> +        get_all_etfs.etfs = market.market_etfs_get().payload.instruments
хорошо, согласен. переделаем это в класс.

2021-03-14 13:59 UTC, Alexander-Serov commented on analysis.py
> +# Load the token
предполагалось, что эта секция будет использоваться разными классами. это просто врапперы вокруг функций из апи. можно перенести в отдельный файл если тебе тут не нравятся?

2021-03-14 13:59 UTC, Alexander-Serov commented on analysis.py
> +        df = pd.DataFrame.from_dict(candles_dict)
правда странно.

2021-03-14 13:59 UTC, Alexander-Serov commented on analysis.py
> +        if figi not in obsolete_tickers.values():
это те, которые перестали торговаться: существуют в истории, но когда пытаешься запросить недавнюю историю, возникает ошибка.

2021-03-14 13:59 UTC, Alexander-Serov commented on analysis.py
> +@lru_cache(maxsize=1000)
Да. В чем вопрос?

2021-03-14 13:59 UTC, Alexander-Serov commented on analysis.py
> +    try:
потому что предыдущая функция делает обратную операцию. в текущем коде я только запрашивал тиккер по фиджи и не наоборот.

2021-03-14 13:59 UTC, Alexander-Serov commented on analysis.py
> +                         weeks=52),
поправим.

2021-03-14 13:59 UTC, Alexander-Serov commented on analysis.py
> +    Get history _data with a given interval for all available ETFs.
починено

2021-03-14 13:59 UTC, Alexander-Serov commented on analysis.py
> +        if 'ticker' not in one_etf_history.columns:
честно, не могу тебе уже сейчас сказать.

2021-03-14 13:59 UTC, Alexander-Serov commented on analysis.py
> +        # Merge into the large table
Да, это правда что должно работать. Предлагаю создать ишшу и в следуюущей сделать. Пока ведь работает уже.

2021-03-14 13:59 UTC, Alexander-Serov commented on analysis.py
> +    need_divide = length > one_period
починил

2021-03-14 13:59 UTC, Alexander-Serov commented on analysis.py
> +    Parameters
Да, давай пользоваться этим. Это Нумпай формат и его легче читать.

2021-03-14 13:59 UTC, Alexander-Serov commented on analysis.py
> +        return np.nan
в смысле предлагаешь ошибку?

2021-03-14 13:59 UTC, Alexander-Serov commented on analysis.py
> +    History.update() # to update the local database of prices
да, починил.

2021-03-14 13:59 UTC, Alexander-Serov commented on analysis.py
> +            self._data.drop(self._data[pd.isna(self._data.time)].index, inplace=True)
я думаю это файлсэйф: если они вдруг нечаянно записались то потом корректно их загружать. 
это правда что может теперь уже и не нужна эта строчка.

2021-03-14 13:59 UTC, Alexander-Serov commented on analysis.py
> +            self._data.time = pd.to_datetime(self._data.time)
надо будет сделать, убедившись что все работает.

2021-03-14 13:59 UTC, Alexander-Serov commented on analysis.py
> +            self._data.time = pd.to_datetime(self._data.time)
ты в принципе можешь тоже что-то сделать.

2021-03-14 13:59 UTC, Alexander-Serov commented on analysis.py
> +        return success
это правда. надо будет поправить.

2021-03-14 13:59 UTC, Alexander-Serov commented on analysis.py
> +        Fetch the latest _data from server starting from 2 last known days.
устарело. исправил.

2021-03-14 13:59 UTC, Alexander-Serov commented on analysis.py
> +        self._tickers = tickers
ЕТФ торгующиеся на рынке могли поменяться. Релоад = фальш говорит лишь о том что он будет использовать кэшированные данные если они доступны. Иначе все запросит заново.

2021-03-14 13:59 UTC, Alexander-Serov commented on analysis.py
> +        :param position what time of day (o, c, h, l) to use to
добавил информацию.

2021-03-14 13:59 UTC, Alexander-Serov commented on analysis.py
> +                                                     filter_52w, ['figi', 'h']].groupby(
починил.

2021-03-14 13:59 UTC, Alexander-Serov commented on analysis.py
> +                          self._data.loc[self._data.time <= filter_1d, ['figi', position]].groupby(
Да, и правда!

2021-03-14 13:59 UTC, Alexander-Serov commented on analysis.py
> +    def recommend_other(self, update: bool = True, _print=False, reload=False):
Ок. Все твои контрибьюшнзы будут высоко нами оценены.

2021-03-14 13:59 UTC, Alexander-Serov commented on analysis.py
> +               f'{THRESHOLD_1D_CHG:.2f}):']
И правда. Для недель вроде то же самое.

2021-03-14 13:59 UTC, Alexander-Serov commented on analysis.py
> +               f'{THRESHOLD_1D_CHG:.2f}):']
Исправил.

2021-03-14 14:00 UTC, Alexander-Serov commented
@sserov Кажется, я согласилися на некоторые предложенные изменения, но они почему-то пропали. Если найдешь непримененный, открой снова, пожалуйста.

2021-03-14 15:07 UTC, Alexander-Serov commented on main-analysis.ipynb
> +{
Комментарий понял, да, там есть неожиданные скачки, но там такие данные грязноватые. Уверен, что Талиб сразу подавится. 
Но что конкретно ты предлагаешь тут?

2021-03-14 15:10 UTC, Alexander-Serov commented on analysis.py
> +        get_all_etfs.etfs = market.market_etfs_get().payload.instruments
Но опять же:
- предполагалось, что эти функции будут использоваться и из других классов.
- если будем менять, может в отдельной ишшу?

2021-03-17 16:58 UTC, sserov commented on .gitignore
> +token
Нет, всё окей

2021-03-17 17:01 UTC, sserov commented on .gitignore
> +token
По-моему, тут была суть в том, что нужно еще временные файлы туда засунуть, а не только токен

2021-03-17 17:07 UTC, sserov commented on main-recommend.py
> +from analysis import History
Думаю, это был просто комментарий

2021-03-17 17:08 UTC, sserov commented on .gitignore
> +token
Например, у меня ПайШарм создает всякую пуфню

2021-03-28 09:35 UTC, sserov commented on requirements.txt
> +colorama
Вроде, пишут, что через pip можно с pypi. Только ссылку надо будет как-то указать.

https://github.com/Awethon/open-api-python-client

2021-03-28 09:40 UTC, sserov commented on main-analysis.ipynb
> +{
Странно, что данные грязные. Надо разобраться, в чем проблема у них

2021-03-28 09:46 UTC, sserov commented on analysis.py
> +# Load the token
Смущало, вроде, что при простом импорте уже выполняется много действий и в том числе создаются папки

2021-03-28 09:57 UTC, sserov commented on analysis.py
> +        get_all_etfs.etfs = market.market_etfs_get().payload.instruments
Ничего не мешает обращаться из других классов к объекту этого класса напрямую или через геттеры/сеттеры. Но всяко лучше, чем к переменной самого модуля, как по мне.

2021-03-28 09:58 UTC, sserov commented on analysis.py
> +        df = pd.DataFrame.from_dict(candles_dict)
Ага

2021-03-28 09:58 UTC, sserov commented on analysis.py
> +        if figi not in obsolete_tickers.values():
А, окей

2021-03-28 09:59 UTC, sserov commented on analysis.py
> +@lru_cache(maxsize=1000)
Вопрос, видимо, был в том, что за кэш. Ну, допустим, он нужен

2021-03-28 10:01 UTC, sserov commented on analysis.py
> +    try:
Окей

2021-03-28 10:03 UTC, sserov commented on analysis.py
> +        # Merge into the large table
Вроде, тут вопрос был в том, что там и так append, но просто в комменте стоит merge

2021-03-28 10:26 UTC, sserov commented on analysis.py
> +        return np.nan
Предлагаю возвращать тот же тип, но только пустой. Или в худшем случае None

2021-03-28 10:29 UTC, sserov commented on analysis.py
> +            self._data.drop(self._data[pd.isna(self._data.time)].index, inplace=True)
Да, возможно, стоит выкинуть

2021-03-28 10:30 UTC, sserov commented on analysis.py
> +            self._data.time = pd.to_datetime(self._data.time)
Да, надо будет сделать

2021-03-28 10:30 UTC, sserov commented on analysis.py
> +            self._data.time = pd.to_datetime(self._data.time)
Я сделать могу, но я предпочитаю сначала знать, что делать, а не просто какие-то мелкие дырки закрывать подряд

2021-03-28 10:37 UTC, sserov commented
Ну вот как раз отвалилось изменение важного косяка с фильтром по 1 дню:

`"1d": self._data.loc[self._data.time <= filter_1d, ["figi", position]]
            .groupby(by="figi")
            .last()[position]
            .to_dict(),`

2021-03-28 11:05 UTC, sserov commented on analysis.py
> +                          self._data.loc[self._data.time <= filter_1d, ['figi', position]].groupby(
@Alexander-Serov Сломалось и не применилось, кажись

2021-03-29 21:50 UTC, Alexander-Serov commented
> Ну вот как раз отвалилось изменение важного косяка с фильтром по 1 дню:
> 
> 
> 
> `"1d": self._data.loc[self._data.time <= filter_1d, ["figi", position]]
> 
>             .groupby(by="figi")
> 
>             .last()[position]
> 
>             .to_dict(),`

Ну что ж, надо будет поправить.

2021-03-29 21:53 UTC, Alexander-Serov commented on .gitignore
> +token
Ну может предложить изменник гитигнора.

2021-03-29 21:55 UTC, Alexander-Serov commented on analysis.py
> +# Load the token
Я думаю папки создавались для того чтобы хранить кэш. Но они могут создаваться при запросе истории с сервера, это правда.

2021-03-29 21:57 UTC, Alexander-Serov commented on analysis.py
> +@lru_cache(maxsize=1000)
Кэш автоматически сохраняет результат функции по запросу в виде словаря. Для функции как здесь соответствие фиги и тикера - это в самый раз так как оно не меняется.

2021-03-29 21:58 UTC, Alexander-Serov commented on analysis.py
> +        # Merge into the large table
Имелся в виду мерж Потому что даты могут перекрываться. ￼

2021-03-29 21:59 UTC, Alexander-Serov commented on analysis.py
> +        return np.nan
Ну не знаю, цена должна быть float. Не известно цена это нан, как обычно￼. Ноне используется обычно для классов нечисленных мне кажется.

2021-03-29 22:00 UTC, Alexander-Serov commented on analysis.py
> +            self._data.drop(self._data[pd.isna(self._data.time)].index, inplace=True)
Ну твое возможно мне особо ничего не говорит: ты либо предлагаешь, либо мы об этом не думаем.￼

2021-03-29 22:01 UTC, Alexander-Serov commented on analysis.py
> +            self._data.time = pd.to_datetime(self._data.time)
Ну теперь ты знаешь. Можешь либо сделать либо ищу создать￼

2021-03-29 22:03 UTC, Alexander-Serov commented on analysis.py
> +        for figi in statistics_sorted.index:
Возможно. Ты опять же можешь предложить.

2021-03-29 22:04 UTC, Alexander-Serov commented on main-recommend.py
> +from analysis import History
Странный абстрактный комментарий.￼

2021-04-04 13:07 UTC, sserov commented on analysis.py
> +            merged.time = pd.to_datetime(self._data.time)
A bug! @Alexander-Serov #9 

```suggestion
            merged.time = pd.to_datetime(merged.time)
```

2021-04-04 13:18 UTC, sserov requested changes
Added a comment about a bug

2021-04-04 14:09 UTC, Alexander-Serov commented on requirements.txt
> +pandas
Меня больше убивает что нельзя этот API который мы используем сюда вставить. Так было бы просто просто устанавливать через пип. ￼

2021-04-04 14:09 UTC, Alexander-Serov commented on .gitignore
> +token
Ну так?

2021-04-04 14:09 UTC, Alexander-Serov commented on analysis.py
> +# Load the token
Починено в #21 ? Закрываем тут?

2021-04-04 14:09 UTC, Alexander-Serov commented on analysis.py
> +        get_all_etfs.etfs = market.market_etfs_get().payload.instruments
Тоже перенес в #21 ?

2021-04-04 14:09 UTC, Alexander-Serov commented on analysis.py
> +        # Merge into the large table
?

2021-04-04 14:09 UTC, Alexander-Serov commented on analysis.py
> +        return np.nan
?

2021-04-04 14:09 UTC, Alexander-Serov commented on analysis.py
> +            self._data.drop(self._data[pd.isna(self._data.time)].index, inplace=True)
?

2021-04-04 14:09 UTC, Alexander-Serov commented on analysis.py
> +            self._data.time = pd.to_datetime(self._data.time)
Ну так что?

2021-04-04 14:09 UTC, Alexander-Serov commented on analysis.py
> +        return success
что с этим делаем в итоге?

2021-04-04 14:09 UTC, Alexander-Serov commented on analysis.py
> +            merged.time = pd.to_datetime(self._data.time)
Вот, это мощно, согласен!

2021-04-04 14:09 UTC, Alexander-Serov commented on analysis.py
> +            old_data = copy.deepcopy(self._data)
на самом деле нет, с тех пор, я нашел еще лучше функцию. 
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.combine_first.html#pandas.DataFrame.combine_first
Может как раз это то, что нужно?

2021-04-04 14:09 UTC, Alexander-Serov commented on analysis.py
> +        for figi in statistics_sorted.index:
?

2021-04-04 14:09 UTC, Alexander-Serov commented on analysis.py
> +    def recommend_other(self, update: bool = True, _print=False, reload=False):
?

2021-04-04 14:09 UTC, Alexander-Serov commented on main-analysis.ipynb
> +{
Так что ты предлагаешь?

2021-04-04 14:09 UTC, Alexander-Serov commented on main-analysis.ipynb
> +{
Есть новости на эту тему после твоих проб?

2021-04-04 14:09 UTC, Alexander-Serov commented on requirements.txt
> +pandas
Так тот новый, что ты предложил еще, и можно будет просто через пип устанавливать.
https://github.com/daxartio/tinvest
Создам ишшу #22.

2021-04-04 14:29 UTC, sserov commented on .gitignore
> +token
```suggestion
token
.idea/
```

2021-04-04 14:30 UTC, sserov commented on requirements.txt
> +colorama
@Alexander-Serov ?

2021-04-04 14:30 UTC, sserov commented on analysis.py
> +                          self._data.loc[self._data.time <= filter_1d, ['figi', position]].groupby(
@Alexander-Serov ?

2021-04-04 14:33 UTC, sserov commented on analysis.py
> +            if (set(figis) - set(value.keys()) - set(obsolete_tickers.values())):
@Alexander-Serov ?

2021-04-04 14:36 UTC, sserov commented on analysis.py
> +        for figi in statistics_sorted.index:
Думаю, пока забьем, потому что эта статистика --- не основная цель сейчас. Пусть пока останется цикл, если работает. Да и фиджей там пока 47 штук, сильно замедлить не должно

2021-04-04 14:38 UTC, sserov commented on analysis.py
> +    def recommend_other(self, update: bool = True, _print=False, reload=False):
Ну тут речь о том, что две функции скопипасчены и просто правила поменяны. Пока забьем по той же причине, что эти рекомендации -- не основная цель

2021-04-04 14:47 UTC, sserov commented on main-analysis.ipynb
> +{
Проб? Нет, это не смотрел, фиксил другое. Вообще, странно, что данные грязные (точно грязные)? Потому что то, что Пуфи смотрел, выглядело более-менее. Если реально грязные, то нужно будет, видимо, сглаживание делать. Об этом ишшу #7

2021-04-04 14:47 UTC, sserov commented on analysis.py
> +# Load the token
Да, это всё починено

2021-04-04 14:48 UTC, sserov commented on analysis.py
> +        get_all_etfs.etfs = market.market_etfs_get().payload.instruments
Закрыто в #21

2021-04-04 14:49 UTC, Alexander-Serov commented on requirements.txt
> +colorama
Не, это все фигня. Не сможем мы объяснить людям, которые захотят использовать, что нужно установить вот как-то сложно. Поэтому хорошо, если мы перейдем #22 в какой-то момент.

2021-04-04 14:49 UTC, sserov commented on analysis.py
> +        if 'ticker' not in one_etf_history.columns:
Странно, ну ладно

2021-04-04 14:50 UTC, sserov commented on analysis.py
> +        # Merge into the large table
Так он закомменчен и изменен в итоге на append?

2021-04-04 14:54 UTC, sserov commented on analysis.py
> +        return np.nan
Ну это имеет разные смыслы. None -- объекта нет, а np.nan -- нечисловое значение. Но да ладно, пусть так

2021-04-04 14:55 UTC, sserov commented on analysis.py
> +            self._data.drop(self._data[pd.isna(self._data.time)].index, inplace=True)
Вроде, это проверяется в def get_etfs_daily_history, и поэтому каждый раз выбрасывать их при загрузке смысла нет. Предлагается эту проверку удалить

2021-04-04 14:57 UTC, sserov commented on analysis.py
> +            self._data.time = pd.to_datetime(self._data.time)
#23

2021-04-04 14:57 UTC, Alexander-Serov commented on analysis.py
> +                          self._data.loc[self._data.time <= filter_1d, ['figi', position]].groupby(
Should be fixed.

2021-04-04 14:57 UTC, sserov commented on analysis.py
> +        return success
Убирай этот success. Даже пайшарм говорит, что она бессмысленная

2021-04-04 14:59 UTC, Alexander-Serov commented on analysis.py
> +            if (set(figis) - set(value.keys()) - set(obsolete_tickers.values())):
Скобки не нужны, да.
Про фиги вроде уже понятно, нет? Это те, что болше не торгуются.

2021-04-04 15:00 UTC, sserov commented on requirements.txt
> +colorama
Окей, тогда оставим как ишшу

2021-04-04 15:00 UTC, sserov commented on analysis.py
> +                          self._data.loc[self._data.time <= filter_1d, ['figi', position]].groupby(
Fixed in #21

2021-04-04 15:01 UTC, sserov commented on analysis.py
> +        df = pd.DataFrame.from_dict(candles_dict)
@Alexander-Serov ?

2021-04-04 15:02 UTC, sserov commented on analysis.py
> +            if (set(figis) - set(value.keys()) - set(obsolete_tickers.values())):
Да, окей. Скобки надо убрать. С фигами ясно

2021-04-07 19:41 UTC, Alexander-Serov commented on analysis.py
> +        # Merge into the large table
Сейчас точно аппенд. И мне кажется, я не менял.
Мердж здесь был в общем смысле добавки и убирания повторяющихся.

2021-04-07 19:49 UTC, sserov commented on analysis.py
> +        # Merge into the large table
Я просил комментарий поменять на аппенд, раз уж он написан

2021-04-07 19:50 UTC, Alexander-Serov commented on analysis.py
> +            self._data.drop(self._data[pd.isna(self._data.time)].index, inplace=True)
Я могу удалит, но предлаегается тебе сначала написат тест, который будет проверят, что ничего не сломается, когда я удалит.

2021-04-07 19:50 UTC, Alexander-Serov commented on analysis.py
> +            self._data.drop(self._data[pd.isna(self._data.time)].index, inplace=True)
Можешь его прямо в ветку коммитнуть.

2021-04-07 19:51 UTC, Alexander-Serov commented on analysis.py
> +        return success
мой не говорит.

2021-04-07 19:52 UTC, sserov commented on analysis.py
> +            self._data.drop(self._data[pd.isna(self._data.time)].index, inplace=True)
Не, давай забьем на тест. Пока не до него

2021-04-07 19:52 UTC, Alexander-Serov commented on analysis.py
> +        return success
но хорошо.

2021-04-07 19:53 UTC, Alexander-Serov commented on analysis.py
> +        # Merge into the large table
Ага, ну хорошо.

2021-04-07 19:55 UTC, Alexander-Serov commented on analysis.py
> +            self._data.drop(self._data[pd.isna(self._data.time)].index, inplace=True)
Вот видишь. Не все так просто выкидывать. Тем более работает...

2021-04-07 19:59 UTC, sserov commented on analysis.py
> +            old_data = copy.deepcopy(self._data)
Кажись, да, это то, что нужно

2021-04-07 20:09 UTC, Alexander-Serov commented on analysis.py
> +            old_data = copy.deepcopy(self._data)
Ну опять же, может и то, что нужно. Но текущая версия уже работает. И писалась год назад. Я считаю что пока можно не обращать на это внимания: если я просто так ее сюда вставлю без теста может сломаться что-то еще. Тут надо сначала тест писать.

2021-04-07 22:47 UTC, sserov commented on analysis.py
> +            old_data = copy.deepcopy(self._data)
Окей, ну это и был коммент год назад про то, что (возможно) стоит улучшить. Если так работает, то, думаю, можно и оставить

2021-04-07 23:37 UTC, sserov commented
Need to revert 900061a because the code was correct and took the close price of the previous day @Alexander-Serov

2021-04-08 20:33 UTC, Alexander-Serov reviewed
Fixed following comments.

2021-04-08 20:34 UTC, sserov approved these changes
Everything okay

2021-04-08 20:35 UTC, merged